services:
  - type: web
    name: littles-blog-api
    env: node
    rootDir: Blog
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
  - type: static_site
    name: littles-blog-client
    env: static
    rootDir: Blog/client
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html 